export const savingsVaultAbi = [
	{
		inputs: [
			{internalType: "address", name: "controller_", type: "address"},
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{
		inputs: [{internalType: "uint40", name: "availableAt", type: "uint40"}],
		name: "CooldownActive",
		type: "error",
	},
	{inputs: [], name: "InsufficientBalance", type: "error"},
	{inputs: [], name: "InvalidDelay", type: "error"},
	{inputs: [], name: "InvalidPercentage", type: "error"},
	{inputs: [], name: "NoPendingWithdrawal", type: "error"},
	{inputs: [], name: "PendingWithdrawal", type: "error"},
	{inputs: [], name: "Reentrancy", type: "error"},
	{inputs: [], name: "TransferFailed", type: "error"},
	{inputs: [], name: "Unauthorized", type: "error"},
	{inputs: [], name: "ZeroValue", type: "error"},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousController",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newController",
				type: "address",
			},
		],
		name: "ControllerUpdated",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "saver",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "operator",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "newBalance",
				type: "uint256",
			},
		],
		name: "Deposited",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousOwner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "OwnerTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "saver",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint16",
				name: "rateBps",
				type: "uint16",
			},
			{
				indexed: false,
				internalType: "uint40",
				name: "withdrawalDelaySeconds",
				type: "uint40",
			},
		],
		name: "SaverConfigured",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "saver",
				type: "address",
			},
		],
		name: "WithdrawalCancelled",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "saver",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint40",
				name: "availableAt",
				type: "uint40",
			},
		],
		name: "WithdrawalRequested",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "saver",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "operator",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "newBalance",
				type: "uint256",
			},
		],
		name: "Withdrawn",
		type: "event",
	},
	{
		inputs: [],
		name: "MAX_WITHDRAWAL_DELAY",
		outputs: [{internalType: "uint40", name: "", type: "uint40"}],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "MIN_WITHDRAWAL_DELAY",
		outputs: [{internalType: "uint40", name: "", type: "uint40"}],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{internalType: "address", name: "saver", type: "address"}],
		name: "balanceOf",
		outputs: [{internalType: "uint256", name: "", type: "uint256"}],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "cancelWithdrawal",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{internalType: "address", name: "saver", type: "address"}],
		name: "cancelWithdrawalFor",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{internalType: "uint16", name: "rateBps", type: "uint16"},
			{
				internalType: "uint40",
				name: "withdrawalDelaySeconds",
				type: "uint40",
			},
		],
		name: "configure",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{internalType: "address", name: "saver", type: "address"},
			{internalType: "uint16", name: "rateBps", type: "uint16"},
			{
				internalType: "uint40",
				name: "withdrawalDelaySeconds",
				type: "uint40",
			},
		],
		name: "configureFor",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "controller",
		outputs: [{internalType: "address", name: "", type: "address"}],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "deposit",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [{internalType: "address", name: "saver", type: "address"}],
		name: "depositFor",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "executeWithdrawal",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{internalType: "address", name: "saver", type: "address"}],
		name: "executeWithdrawalFor",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{internalType: "address", name: "saver", type: "address"}],
		name: "getAccount",
		outputs: [
			{internalType: "uint16", name: "rateBps", type: "uint16"},
			{internalType: "uint40", name: "withdrawalDelay", type: "uint40"},
			{internalType: "uint256", name: "balance", type: "uint256"},
			{internalType: "uint256", name: "totalDeposited", type: "uint256"},
			{internalType: "uint256", name: "totalWithdrawn", type: "uint256"},
			{
				internalType: "uint256",
				name: "pendingWithdrawalAmount",
				type: "uint256",
			},
			{
				internalType: "uint40",
				name: "pendingAvailableAt",
				type: "uint40",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [{internalType: "address", name: "", type: "address"}],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{internalType: "uint256", name: "amount", type: "uint256"}],
		name: "requestWithdrawal",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{internalType: "address", name: "saver", type: "address"},
			{internalType: "uint256", name: "amount", type: "uint256"},
		],
		name: "requestWithdrawalFor",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{internalType: "address", name: "newController", type: "address"},
		],
		name: "setController",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{internalType: "address", name: "newOwner", type: "address"}],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{stateMutability: "payable", type: "receive"},
] as const;

export type SavingsVaultAbi = typeof savingsVaultAbi;
